In [95]:
import numpy as np
import math
import time
import matplotlib.pyplot as plt
from scipy.linalg import hadamard
from scipy import linalg
from sklearn.utils import extmath
from scipy.misc import toimage
import cv2
from PIL import Image
from scipy.sparse.linalg import svds
from scipy.sparse import random as spr

# Matrix multuplication

In [2]:
#this method is used for calculate the optimal probability set in the randomized matrix multiplication algorithm.
def max_fnorm(A,B):
    fnorms=np.zeros(A.shape[1])
    nsum=0
    for i in range(A.shape[1]):
        fnorm=np.linalg.norm(A[:,i]) * np.linalg.norm(B[i,:])
        fnorms[i]=fnorm
        nsum=nsum+fnorm
    return fnorms/nsum

In [3]:
#random matrix multiplication method
def rand_matrix_mul(A,B,c,probability):
    col=np.array(range(A.shape[1]))
    msum=np.zeros([A.shape[0],B.shape[1]])
    for i in range(c):
        j=np.random.choice(col,p=probability)
        Aj=np.reshape(A[:,j],[len(A[:,j]),1])
        Bj=np.reshape(B[j,:],[1,len(B[j,:])])
        mul=np.matmul(Aj,Bj)/(c*p[j])
        msum=msum+mul
    return msum

In [17]:
#Create the list to store the result, each size of n (A' column number and B's row number) has one 
#element in the list. rmm for randomized matrix multiplication and emm for exact matrix multiplication.
#p_time for the time used to get the probability
rmm_time = [None]*10
rmm_accu = [None]*10
emm_time = [None]*10
emm_norm = [None]*10
p_time = [None]*10

#For each calculation, we want to repeat 30 times and take average to get a more accurate description 
#of the method
repeat_times = 40
#Create the array of different sampling sizes.
C = np.array(range(50,501,50))
#set initial value for n
init_n = 30000

In [18]:
#Doing the test for the first 5 sizes
for i in range(5):
    #set size of A,B, and the arrays to store the time and accuracy for different sizes of A and B.
    A = np.random.rand(700,init_n+i*30000) #elements of A is in [0,1)
    B = np.random.rand(init_n+i*30000,700) #elements of B is in [0,1)
    times=np.zeros(len(C)) #same n, different c
    errors=np.zeros(len(C)) #same n, different c

    #calculate the exact matrix multiplication
    start=time.time()
    exact=np.matmul(A,B)
    end=time.time()
    emm_time[i] = end-start
    extfnorm=np.linalg.norm(exact)
    emm_norm[i] = extfnorm*extfnorm

    #get the probability
    start = time.time()
    p=max_fnorm(A,B)
    end = time.time()
    p_time[i] = end-start
    
    #calculate the random matrix multiplication for each value of n (taking the average)
    index=0
    for c in C:
        timS = np.zeros(repeat_times) #same n, same c, for average
        errS = np.zeros(repeat_times) #same n, same c, for average
        for k in range(repeat_times):
            start=time.time()
            random=rand_matrix_mul(A,B,c,p)
            end=time.time()
            error=np.linalg.norm(exact-random)
            timS[k] = end-start
            errS[k] = error*error/(extfnorm*extfnorm)
        times[index]=np.average(timS)
        errors[index]=np.average(errS)
        index+=1
        
    #adding the result to the rmm_time and rmm_accu
    rmm_time[i] = times
    rmm_accu[i] = errors

In [24]:
#Doing the test for the next 5 sizes
for i in range(5,10,1):
    #set size of A,B, and the arrays to store the time and accuracy for different sizes of A and B.
    A = np.random.rand(700,init_n+i*30000) #elements of A is in [0,1)
    B = np.random.rand(init_n+i*30000,700) #elements of B is in [0,1)
    times=np.zeros(len(C)) #same n, different c
    errors=np.zeros(len(C)) #same n, different c

    #calculate the exact matrix multiplication
    start=time.time()
    exact=np.matmul(A,B)
    end=time.time()
    emm_time[i] = end-start
    extfnorm=np.linalg.norm(exact)
    emm_norm[i] = extfnorm*extfnorm

    #get the probability
    start = time.time()
    p=max_fnorm(A,B)
    end = time.time()
    p_time[i] = end-start
    
    #calculate the random matrix multiplication for each value of n (taking the average)
    index=0
    for c in C:
        timS = np.zeros(repeat_times) #same n, same c, for average
        errS = np.zeros(repeat_times) #same n, same c, for average
        for k in range(repeat_times):
            start=time.time()
            random=rand_matrix_mul(A,B,c,p)
            end=time.time()
            error=np.linalg.norm(exact-random)
            timS[k] = end-start
            errS[k] = error*error/(extfnorm*extfnorm)
        times[index]=np.average(timS)
        errors[index]=np.average(errS)
        index+=1
        
    #adding the result to the rmm_time and rmm_accu
    rmm_time[i] = times
    rmm_accu[i] = errors

In [27]:
rmm_timeC = [None]*10
rmm_accuC = [None]*10
emm_timeC = [None]*10
emm_normC = [None]*10
p_timeC = [None]*10

In [29]:
#Doing the test for the another 10 sizes
for i in range(10,20,1):
    #set size of A,B, and the arrays to store the time and accuracy for different sizes of A and B.
    A = np.random.rand(700,init_n+i*30000) #elements of A is in [0,1)
    B = np.random.rand(init_n+i*30000,700) #elements of B is in [0,1)
    times=np.zeros(len(C)) #same n, different c
    errors=np.zeros(len(C)) #same n, different c

    #calculate the exact matrix multiplication
    start=time.time()
    exact=np.matmul(A,B)
    end=time.time()
    emm_timeC[i-10] = end-start
    extfnorm=np.linalg.norm(exact)
    emm_normC[i-10] = extfnorm*extfnorm

    #get the probability
    start = time.time()
    p=max_fnorm(A,B)
    end = time.time()
    p_timeC[i-10] = end-start
    
    #calculate the random matrix multiplication for each value of n (taking the average)
    index=0
    for c in C:
        timS = np.zeros(repeat_times) #same n, same c, for average
        errS = np.zeros(repeat_times) #same n, same c, for average
        for k in range(repeat_times):
            start=time.time()
            random=rand_matrix_mul(A,B,c,p)
            end=time.time()
            error=np.linalg.norm(exact-random)
            timS[k] = end-start
            errS[k] = error*error/(extfnorm*extfnorm)
        times[index]=np.average(timS)
        errors[index]=np.average(errS)
        index+=1
        
    #adding the result to the rmm_time and rmm_accu
    rmm_timeC[i-10] = times
    rmm_accuC[i-10] = errors

In [177]:
print(p_timeC)

[7.973589181900024, 7.5893590450286865, 8.5105299949646, 9.076717853546143, 9.892645120620728, 9.98530912399292, 11.172114133834839, 11.547385215759277, 19.08427906036377, 109.73252201080322]


# Low rank matrix approximation

In [115]:
#Calculate a Hadamard Transformation 
def hadamardM(H,n,index):
    if index==n:
        return H
    if index==1:
        H[0,0]=1
        H[0,1]=1
        H[1,0]=1
        H[1,1]=-1
    else:
        H[0:index,index:index+index]=H[0:index,0:index]
        H[index:index+index,0:index]=H[0:index,0:index]
        H[index:index+index,index:index+index]=H[0:index,0:index]*(-1)
    index=2*index
    return hadamardM(H,n,index)

In [116]:
#Calculate low rank matrix approximation
def low_rank_matrix(A,k):
    #calculating c with c0=0.005 and e=0.25
    n=A.shape[1]
    co=0.005
    c=int(co*k*math.log(n)*(math.log(k/0.0625)+math.log(math.log(n)))/0.0625)+2
    H=hadamard(n)/math.sqrt(n)
    C=range(n)
    chosen=np.random.choice(C,size=c)
    D=np.zeros([n,n])
    for i in range(n):
        D[i,i]=np.random.choice([1,-1])
    #AD=np.matmul(A,D)
    H_sample=np.zeros([A.shape[0],c])
    for i in range(c):
        H_sample[:,i]=H[:,chosen[i]]
    approx = np.matmul(A, np.matmul(D,H_sample))
    Q=linalg.orth(approx)
    B=np.matmul(np.matrix.transpose(Q),A)
    leftB=np.linalg.svd(B)[0][:,0:k]
    approximation=np.matmul(Q,leftB)
    return approximation

In [117]:
#calculate how sparse is A
def sparcity(A):
    return np.count_nonzero(A)/(A.shape[0]*A.shape[1])

In [124]:
#create lists to store results
size_c = 5
rlrma_time_size=[None]*size_c #for randomized low rank matrix approximation
rlrma_accu_size=[None]*size_c
svd_time_size=[None]*size_c #for svd
svd_accu_size=[None]*size_c
A_norm=np.zeros(size_c) #for A's norm
A_sparcity=np.zeros(size_c)

#initialize some constants
K=np.arange(5,51,5)
init_n_app = 512
size = init_n_app
repeatTime = 15

In [125]:
#create lists to store results
rlrma_time_sps=[None]*size_c #for randomized low rank matrix approximation
rlrma_accu_sps=[None]*size_c
svd_time_sps=[None]*size_c #for svd
svd_accu_sps=[None]*size_c
A_norm_sps=np.zeros(size_c) #for A's norm
A_sparcity_sps=np.zeros(size_c)

#initialize some constants
size_sps = 4096

In [126]:
#test the algorithm for different size of A but similar sparcity.
for i in range(size_c):
    #create random matrix A and record it's norm and sparcity
    A = np.random.rand(size,size)
    A_norm[i]=np.linalg.norm(A)
    A_sparcity[i]=sparcity(A)
    #create list to store result for different k but same A
    timeRA=np.zeros(len(K))
    accuRA = np.zeros(len(K))
    timeEA=np.zeros(len(K))
    accuEA = np.zeros(len(K))
    
    index=0
    #test for different k values
    for kn in K:
        #for low rank approximation
        timeR=np.zeros(repeatTime)
        accuR=np.zeros(repeatTime)
        
        start=time.time()
        u,s,vt=svds(A,k=kn)
        end=time.time()
        timeEA[index] = end-start
        accuEA[index] = abs(np.linalg.norm(np.matmul(np.matmul(u,np.matrix.transpose(u)),A))-A_norm[i])
        
        #repeat random method for several times
        for j in range(repeatTime):
            start=time.time()
            resultR=low_rank_matrix(A,kn)
            end=time.time()
            timeR[j]=end-start
            accR=abs(np.linalg.norm(np.matmul(np.matmul(resultR,np.matrix.transpose(resultR)),A))-A_norm[i])
            accuR[j]=accR
        timeRA[index] = np.average(timeR)
        accuRA[index] = np.average(accuR)
        index+=1
        
    rlrma_time_size[i] = timeRA
    print(timeRA)
    rlrma_accu_size[i] = accuRA
    svd_time_size[i] = timeEA
    print(timeEA)
    svd_accu_size[i] = accuEA
    size = size*2


[0.03457023 0.05899908 0.04400646 0.04799468 0.05028089 0.05454906
 0.06313732 0.06927455 0.07631362 0.08338923]
[0.05694318 0.04154015 0.04442382 0.07854009 0.09172082 0.04697394
 0.04941607 0.05840492 0.06612492 0.07995796]
[0.10110799 0.13773562 0.17062922 0.20227076 0.24142297 0.27354943
 0.28540061 0.28567897 0.30312726 0.33741186]
[0.27057195 0.23535204 0.26869607 0.29616618 0.32420111 0.32424331
 0.3788619  0.40644813 0.43024087 0.45056415]
[0.37664946 0.53321792 0.68782825 0.84603413 1.0230951  1.06373994
 1.0487813  1.04265089 1.13721835 1.20740197]
[1.14019299 1.21831703 1.44861484 1.28325987 1.47444582 1.66918302
 1.7987361  1.92874789 2.00186706 2.05354214]
[1.6027857  2.23249639 2.94931959 3.78930128 3.77456614 3.86441253
 4.09273847 4.36982155 4.68454701 4.88366299]
[6.02596593 6.41597295 6.59312391 6.689852   7.46846986 7.82608294
 8.4608469  9.31027913 9.39847612 9.95330286]
[ 6.83180291  9.78856341 12.89541143 16.08414399 17.13604843 17.43414896
 18.15876252 18.4771575

In [127]:
#test the algorithm for same size of A but different sparcity.
for i in range(size_c):
    #create random matrix A and record it's norm and sparcity
    ds = (i+1)/size_c
    A = spr(size_sps,size_sps,density=ds).A
    A_norm_sps[i]=np.linalg.norm(A)
    A_sparcity_sps[i]=ds
    #create list to store result for different k but same A
    timeRA=np.zeros(len(K))
    accuRA = np.zeros(len(K))
    timeEA=np.zeros(len(K))
    accuEA = np.zeros(len(K))
    
    index=0
    #test for different k values
    for kn in K:
        #for low rank approximation
        timeR=np.zeros(repeatTime)
        accuR=np.zeros(repeatTime)
        
        start=time.time()
        u,s,vt=svds(A,k=kn)
        end=time.time()
        timeEA[index] = end-start
        accuEA[index] = abs(np.linalg.norm(np.matmul(np.matmul(u,np.matrix.transpose(u)),A))-A_norm[i])
        
        #repeat random method for several times
        for j in range(repeatTime):
            start=time.time()
            resultR=low_rank_matrix(A,kn)
            end=time.time()
            timeR[j]=end-start
            accR=abs(np.linalg.norm(np.matmul(np.matmul(resultR,np.matrix.transpose(resultR)),A))-A_norm[i])
            accuR[j]=accR
        timeRA[index] = np.average(timeR)
        accuRA[index] = np.average(accuR)
        index+=1
        
    rlrma_time_sps[i] = timeRA
    rlrma_accu_sps[i] = accuRA
    svd_time_sps[i] = timeEA
    svd_accu_sps[i] = accuEA


In [128]:
print(rlrma_accu_sps)

[array([ 69.50609347,  98.87011465, 109.89019179, 117.5469479 ,
       122.40993041, 127.4857122 , 131.88578466, 136.31782911,
       140.66850666, 144.44922918]), array([185.64615925, 213.78820968, 223.65245874, 230.34904873,
       235.11019483, 239.37826362, 242.96211572, 246.66257842,
       250.25253279, 253.64918849]), array([16.41378433, 33.73752404, 42.3496727 , 48.02131175, 51.27167255,
       54.68077636, 57.84330794, 60.70140166, 63.57165304, 66.26725381]), array([749.9252975 , 735.2487875 , 728.82776983, 725.32526775,
       722.7598807 , 720.3047342 , 717.95671331, 715.93730666,
       713.9125615 , 711.89082684]), array([2697.11697212, 2687.46917653, 2683.58242607, 2681.08892408,
       2679.30188899, 2677.74943022, 2676.27839663, 2675.04199516,
       2673.76027747, 2672.4669841 ])]


In [129]:
print(svd_accu_sps)

[array([119.05989834, 124.4846825 , 129.77343006, 134.9517288 ,
       140.01696316, 144.99292222, 149.87784058, 154.67672551,
       159.38428896, 164.01049504]), array([232.27413443, 236.79476186, 241.22561948, 245.59568905,
       249.9029826 , 254.15888791, 258.36055974, 262.51404576,
       266.61481536, 270.66515255]), array([49.28175726, 52.84643225, 56.36122372, 59.8308706 , 63.26118365,
       66.66031501, 70.02053099, 73.34275186, 76.63241733, 79.89055794]), array([724.28489795, 721.67986588, 719.11318762, 716.57444028,
       714.06389372, 711.57696375, 709.11266222, 706.66977499,
       704.24994163, 701.85095651]), array([2680.2642446 , 2678.63907145, 2677.0337042 , 2675.44636585,
       2673.87151114, 2672.31298832, 2670.76718723, 2669.23456225,
       2667.71323911, 2666.20371892])]


In [130]:
print(rlrma_time_sps)

[array([1.78211521, 2.28722041, 2.98382603, 3.719148  , 3.80804501,
       3.93214734, 4.21283153, 4.55269009, 4.69383033, 4.92570446]), array([1.62652095, 2.27393765, 2.99644049, 3.91035239, 3.74436073,
       4.08704343, 4.23999669, 4.49931102, 4.71563509, 4.96501338]), array([1.64057695, 2.28405096, 3.00244883, 3.69555813, 3.79803284,
       3.89174445, 4.26449738, 4.4743427 , 4.70943101, 4.95535622]), array([1.62497783, 2.24467808, 2.96976663, 3.65821231, 3.71309471,
       3.85009445, 4.15268771, 4.45512075, 4.77574684, 4.85250669]), array([1.61893539, 2.2657719 , 2.99368862, 3.70636039, 3.73721649,
       3.89329443, 4.17652701, 4.4934806 , 4.83032284, 4.88843528])]


In [131]:
print(svd_time_sps)

[array([6.683079  , 6.25061202, 6.9702363 , 7.34551764, 7.86321592,
       9.08610511, 8.33382297, 8.65848279, 9.43974829, 9.98487282]), array([5.90855813, 5.58460808, 6.82760096, 7.38499188, 7.58847904,
       8.16746116, 8.36179113, 9.06923819, 9.61984181, 9.84480381]), array([ 5.0510819 ,  6.50432301,  6.48615026,  7.10431409,  7.38406897,
        7.72405887,  8.29976606,  8.79751658,  9.35012364, 10.02719402]), array([5.47329259, 6.59975886, 7.36514616, 6.91198897, 7.53412008,
       7.70068407, 8.56531   , 8.92280197, 9.41755986, 9.84124398]), array([5.54440713, 6.68141723, 6.89076805, 7.35118604, 7.26051688,
       7.96318698, 8.59062409, 9.01655507, 9.1408689 , 9.45828891])]


In [132]:
print(A_norm_sps)

[1057.9220689  1495.21610142 1831.45228784 2115.00659131 2364.74334825]


In [133]:
print(A_sparcity_sps)

[0.2 0.4 0.6 0.8 1. ]


# Low Rank Approximation for PSD

In [135]:
from numpy.linalg import matrix_rank
from numpy.linalg import inv
from scipy.linalg import eigh
from numpy import fft
from numpy.linalg import pinv


In [136]:
#low rank approximation for SPSD with sketches
def get_u(A):
    k = matrix_rank(A)
    projection = np.matmul(np.matmul(A,inv(np.matmul(A.transpose(),A))),A.transpose())
    max = projection[0,0]
    for i in range(projection.shape[0]):
        if projection[i,i]>max:
            max = projection[i,i]
    n = A.shape[0]
    u = n/k*max
    return u
    
def get_l_ny(u,k,epslon,delta,inc):
    min_l = 2*u*(1/(epslon*epslon))*k*math.log(k/delta)
    return math.ceil(min_l + inc)

def get_l_gs(k,epslon):
    return math.ceil((1+epslon*epslon)*k)
    
def nystrom(n,l):
    I = np.identity(n)
    #print(n)
    #print(l)
    choice = np.random.choice(n, size=l, replace=False)
    S = I[:,choice]
    return S

def gaussian(n,l):
    return np.random.normal(size=(n,l))

def approximation(A,l,extension):
    if extension == 0:
        S = nystrom(A.shape[0],l)
    elif extension == 1:
        S = srft(A.shape[0],l)
    elif extension == 2:
        S = gaussian(A.shape[0],l)
    C = np.matmul(A,S)
    W = np.matmul(S.transpose(),np.matmul(A,S))
    Winv = pinv(W)
    approx = np.matmul(C,np.matmul(Winv,C.transpose()))
    return approx

In [156]:
#create lists to store results
size_ct = 2
ny_time_size=[None]*size_ct #for nystrom extension
ny_accu_size=[None]*size_ct
gs_time_size=[None]*size_ct #for gaussian extension
gs_accu_size=[None]*size_ct
esvd_time_size=[None]*size_ct #for svd
esvd_accu_size=[None]*size_ct
psd_norm=np.zeros(size_ct) #for A's norm
psd_sparcity=np.zeros(size_ct)

#initialize some constants
K=np.arange(5,31,5)
init_n_app = 3000
size = init_n_app
repeatTime = 10
epslon = 0.9
delta = 0.1

In [163]:
#test the algorithm for different size of A but similar sparcity.
for i in range(size_ct):
    #create random matrix A and record it's norm and sparcity
    size = init_n_app+i*2000
    A = np.random.rand(size,size)
    A = np.matmul(A.transpose(),A)
    psd_norm[i]=np.linalg.norm(A)
    psd_sparcity[i]=sparcity(A)
    #create list to store result for different k but same A
    timeNA=np.zeros(len(K))
    accuNA=np.zeros(len(K))
    timeGA=np.zeros(len(K))
    accuGA=np.zeros(len(K))
    timeEA=np.zeros(len(K))
    accuEA=np.zeros(len(K))
    #get coherence u
    inputU = get_u(A)
    
    index=0
    #test for different k values
    for kn in K:
        timeN=np.zeros(repeatTime)
        accuN=np.zeros(repeatTime)
        timeG=np.zeros(repeatTime)
        accuG=np.zeros(repeatTime)
        
        
        #for svd
        start=time.time()
        u,s,vt=svds(A,k=kn)
        end=time.time()
        timeEA[index] = end-start
        accuEA[index] = abs(np.linalg.norm(np.matmul(np.matmul(u,np.matrix.transpose(u)),A))-psd_norm[i])
        
        
        
        #repeat nystrom extension for several times
        l=get_l_ny(inputU,kn,epslon,delta,0)
        print("ny:  ",l)
        for j in range(repeatTime):
            start=time.time()
            resultR=approximation(A,l,0)
            end=time.time()
            timeN[j]=end-start
            accR=abs(np.linalg.norm(resultR)-psd_norm[i])
            accuN[j]=accR
        timeNA[index] = np.average(timeN)
        accuNA[index] = np.average(accuN)
        
        #repeat guassian extension for several times
        l=get_l_gs(kn,epslon)
        print("gs:  ",l)
        for j in range(repeatTime):
            start=time.time()
            resultR=approximation(A,l,2)
            end=time.time()
            timeG[j]=end-start
            accR=abs(np.linalg.norm(resultR)-psd_norm[i])
            accuG[j]=accR
        timeGA[index] = np.average(timeG)
        accuGA[index] = np.average(accuG)
        
        index+=1
        
    ny_time_size[i] = timeNA
    ny_accu_size[i] = accuNA
    gs_time_size[i] = timeGA
    gs_accu_size[i] = accuGA
    esvd_time_size[i] = timeEA
    esvd_accu_size[i] = accuEA


ny:   49
gs:   10
ny:   115
gs:   19
ny:   187
gs:   28
ny:   263
gs:   37
ny:   343
gs:   46
ny:   425
gs:   55
[0.13984497 0.23019464 0.2524698  0.46157472 0.50496194 0.68923197]
[0.087328   0.11931291 0.08931139 0.09838281 0.10558391 0.11706512]
[2.07266998 2.35358095 2.43203926 3.00338888 2.55007195 3.07142711]
ny:   50
gs:   10
ny:   116
gs:   19
ny:   189
gs:   28
ny:   267
gs:   37
ny:   348
gs:   46
ny:   431
gs:   55
[0.18992476 0.20510077 0.33153341 0.33809586 0.435656   0.57960956]
[0.11893718 0.09082084 0.10804198 0.09705601 0.1038291  0.1142823 ]
[1.68261933 2.41987395 2.30344486 2.51653099 2.40967607 2.62032819]


In [167]:
print(ny_accu_size)
print(gs_accu_size)
print(esvd_accu_size)
print(psd_norm)

[array([2405.57124138, 1708.51549274, 1377.88779336, 1191.17865132,
       1048.59838911,  940.8899683 ]), array([522.98621645, 457.61196009, 408.3061304 , 367.24045359,
       329.55072531, 300.45557165])]
[array([3716.77630507, 3345.46171055, 2863.37492046, 2692.71553767,
       2382.53717148, 2409.31333911]), array([590.24276342, 569.2565704 , 550.80059889, 538.52657486,
       524.04689577, 512.71475944])]
[array([1064.11635032, 1048.34105462, 1033.14840283, 1018.47058364,
       1004.09669   ,  990.03955473]), array([471.58689298, 456.58304943, 443.07567392, 430.79996114,
       419.52945744, 409.09502281])]
[4756.16329531  646.20427434]


In [175]:
#create lists to store results
size_ct = 7
ny_time_sps=[None]*size_ct #for nystrom extension
ny_accu_sps=[None]*size_ct
gs_time_sps=[None]*size_ct #for gaussian extension
gs_accu_sps=[None]*size_ct
esvd_time_sps=[None]*size_ct #for svd
esvd_accu_sps=[None]*size_ct
psd_norm_sps=np.zeros(size_ct) #for A's norm
psd_sparcity_sps=np.zeros(size_ct)

#initialize some constants
K=np.arange(5,31,5)
size = 5000
repeatTime = 10
epslon = 0.9
delta = 0.1

In [176]:
#test the algorithm for same size of A but different sparcity.
count=0
for i in range(size_ct):
    #create random matrix A and record it's norm and sparcity
    ds = (i+1)/int(size_ct+1)
    A = spr(3000,3000,density=ds).A
    A = np.matmul(A.transpose(),A)
    psd_norm_sps[i]=np.linalg.norm(A)
    psd_sparcity_sps[i]=sparcity(A)
    #create list to store result for different k but same A
    timeNA=np.zeros(len(K))
    accuNA=np.zeros(len(K))
    timeGA=np.zeros(len(K))
    accuGA=np.zeros(len(K))
    timeEA=np.zeros(len(K))
    accuEA=np.zeros(len(K))
    #get coherence u
    inputU = get_u(A)
    
    index=0
    #test for different k values
    for kn in K:
        print(count)
        count+=1
        timeN=np.zeros(repeatTime)
        accuN=np.zeros(repeatTime)
        timeG=np.zeros(repeatTime)
        accuG=np.zeros(repeatTime)
        
        
        #for svd
        start=time.time()
        u,s,vt=svds(A,k=kn)
        end=time.time()
        timeEA[index] = end-start
        accuEA[index] = abs(np.linalg.norm(np.matmul(np.matmul(u,np.matrix.transpose(u)),A))-psd_norm[i])
        
        
        
        #repeat nystrom extension for several times
        l=get_l_ny(inputU,kn,epslon,delta,0)
        #print("ny:  ",l)
        for j in range(repeatTime):
            start=time.time()
            resultR=approximation(A,l,0)
            end=time.time()
            timeN[j]=end-start
            accR=abs(np.linalg.norm(resultR)-psd_norm[i])
            accuN[j]=accR
        timeNA[index] = np.average(timeN)
        accuNA[index] = np.average(accuN)
        
        #repeat guassian extension for several times
        l=get_l_gs(kn,epslon)
        #print("gs:  ",l)
        for j in range(repeatTime):
            start=time.time()
            resultR=approximation(A,l,2)
            end=time.time()
            timeG[j]=end-start
            accR=abs(np.linalg.norm(resultR)-psd_norm[i])
            accuG[j]=accR
        timeGA[index] = np.average(timeG)
        accuGA[index] = np.average(accuG)
        
        index+=1
        
    ny_time_sps[i] = timeNA
    ny_accu_sps[i] = accuNA
    gs_time_sps[i] = timeGA
    gs_accu_sps[i] = accuGA
    esvd_time_sps[i] = timeEA
    esvd_accu_sps[i] = accuEA


0
1
2
3
4
5
6
7
8
9
10
11
12


IndexError: index 2 is out of bounds for axis 0 with size 2

# SVM

In [17]:
import pandas as pd

In [18]:
#import data with pandas
data = pd.read_csv("voice.csv")
data.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [112]:
data.shape

(3168, 21)

## split X and Y
X = data.iloc[:,:-1]
Y = data.iloc[:,-1]

In [21]:
#preprocessing data
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
#encode Y
le = preprocessing.LabelEncoder()
le.fit(["male","female"])
Y = le.transform(Y)

In [26]:
#split train and test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [27]:
#standartdize X
scaler = preprocessing.StandardScaler().fit(X_train)
X_trainS = scaler.transform(X_train)
X_testS = scaler.transform(X_test)

In [57]:
#train with model with linear kernel without approximation
from sklearn import svm
svcl = svm.SVC(kernel='linear')
start = time.time()
svcl.fit(X_train,y_train)
end = time.time()
print("time used to fit the model with linear kernel without approximation: ",end-start)

time used to fit the model with linear kernel without approximation:  3.52838397026062


In [113]:
#accuracy score for linear kernel without approximation
from sklearn.metrics import accuracy_score
y_pred = svcl.predict(X_test)
print("accuracy of the model with linear kernel without approximation: ",accuracy_score(y_test, y_pred))

accuracy of the model with linear kernel without approximation:  0.9148264984227129


In [104]:
#calculate gram matrix
train = np.asarray(X_trainS)
gram = np.matmul(train,train.transpose())
gram.shape
k = 10
epslon=0.9

In [105]:
#approximate the gram matrix with the sketch and guassian extension
l=get_l_gs(k,epslon)
start=time.time()
gramapprox = approximation(gram,l,2)
end = time.time()
print("time used to approximate with gaussian extension: ",end-start)

time used to approximate with gaussian extension:  0.1310422420501709


In [106]:
#fit model with linear kernel with approximation
svcl_app_g = svm.SVC(kernel='precomputed')
start = time.time()
svcl_app_g.fit(gramapprox,y_train)
end = time.time()
print("time used to fit the model with linear kernel with gaussian approximation: ",end-start)

time used to fit the model with linear kernel with gaussian approximation:  0.07590723037719727


In [114]:
#accuracy score for linear kernel with gaussian approximation
kernel_test = np.dot(X_testS, X_trainS.T)
y_pred_app = svcl_app.predict(kernel_test)
print("accuracy of the model with linear kernel with gaussian approximation: ",accuracy_score(y_test, y_pred_app))

accuracy of the model with linear kernel with gaussian approximation:  0.9779179810725552


In [99]:
u=get_u(gram)

In [116]:
#approximate the gram matrix with the sketch and nystrom extension
#l_n=get_l_ny(u,k,epslon,0.9,0)
start=time.time()
gramapproxn = approximation(gram,2*k,0)
end = time.time()
print("time used to approximate with nystrom extension: ",end-start)

time used to approximate with nystrom extension:  0.21469998359680176


In [109]:
#fit model with linear kernel with approximation
svcl_app_n = svm.SVC(kernel='precomputed')
start = time.time()
svcl_app_n.fit(gramapproxn,y_train)
end = time.time()
print("time used to fit the model with linear kernel with gaussian approximation: ",end-start)

time used to fit the model with linear kernel with gaussian approximation:  0.08150100708007812


In [117]:
#accuracy score for linear kernel with gaussian approximation
kernel_test = np.dot(X_testS, X_trainS.T)
y_pred_app = svcl_app_n.predict(kernel_test)
print("accuracy of the model with linear kernel with gaussian approximation: ",accuracy_score(y_test, y_pred_app))

accuracy of the model with linear kernel with gaussian approximation:  0.9779179810725552


In [111]:
print(gramapproxn-gramapprox)

[[ 1.14290799e-11  9.23705556e-13 -2.44249065e-12 ...  1.05204734e-12
   3.08375547e-12 -4.40536496e-12]
 [-4.48707738e-12  1.11199938e-12  1.24766864e-12 ...  2.27512453e-13
  -3.56159546e-12  1.43662859e-12]
 [ 6.56363852e-12  1.48769885e-12 -1.39621648e-12 ...  1.05759845e-12
   1.34470213e-12 -2.34456898e-12]
 ...
 [ 1.42552636e-12 -1.88515870e-13 -1.68931535e-12 ...  3.09086090e-13
  -1.31539224e-12 -1.62536651e-12]
 [-1.26618716e-11 -8.17124146e-14  2.92565971e-12 ... -1.89981364e-12
  -7.70938868e-13  4.20108393e-12]
 [ 3.40261153e-12 -1.83852933e-13 -1.95399252e-12 ...  8.23341395e-13
  -1.68398628e-12 -1.21858079e-12]]


In [172]:
import json

with open('result.json') as f:
  data = json.load(f)

In [173]:
print(data)

{'version_major': 2, 'version_minor': 0, 'state': {}}
